# Generated by sila2.code_generator; sila2.__version__: 0.10.1

from typing import Optional
from uuid import UUID

from sila2.server import SilaServer

from .feature_implementations.chemspeedoperator_impl import ChemSpeedOperatorImpl
from .generated.chemspeedoperator import ChemSpeedOperatorFeature


class Server(SilaServer):
    def __init__(self, server_uuid: Optional[UUID] = None):
        # TODO: fill in your server information
        super().__init__(
            server_name="TODO",
            server_type="TODO",
            server_version="0.1",
            server_description="TODO",
            server_vendor_url="https://gitlab.com/SiLA2/sila_python",
            server_uuid=server_uuid,
        )

        self.chemspeedoperator = ChemSpeedOperatorImpl(self)
        self.set_feature_implementation(ChemSpeedOperatorFeature, self.chemspeedoperator)
