# Generated by sila2.code_generator; sila2.__version__: 0.10.3

from typing import Optional
from uuid import UUID

from sila2.server import SilaServer

from .feature_implementations.opticstable_impl import OpticsTableImpl
from .generated.opticstable import OpticsTableFeature


class Server(SilaServer):
    def __init__(self, server_uuid: Optional[UUID] = None):
        # TODO: fill in your server information
        super().__init__(
            server_name="Sila2-opticstable",
            server_type="Characterization",
            server_version="0.1",
            server_description="sila2 server for the optcs table",
            server_vendor_url="https://gitlab.com/SiLA2/sila_python",
            server_uuid=server_uuid,
        )

        self.opticstable = OpticsTableImpl(self)
        self.set_feature_implementation(OpticsTableFeature, self.opticstable)
