# Generated by sila2.code_generator; sila2.__version__: 0.10.1
# required for editable setuptools installations: https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
from setuptools import setup

setup()
